export const constURL = {
    HOME: "/",
    ABOUT: "/about",
    MBA_ADMISSIONS: "/mba-admissions/",
    SIGNIN: "/signin/",
    REGISTER: "/register/",
    ONBOARDING_STEP_1: "/register/onboarding-step-1/",
    ONBOARDING_STEP_2: "/register/onboarding-step-2/",
    ONBOARDING_STEP_3: "/register/onboarding-step-3/",
    FORGOT_PASSWORD: "/forgot-password/",
    VERIFY_OTP: "/verify-otp/",
    CAREERS: "/careers/",
    CONTACT: "/contact",
    FAQ: "/faq/",
    BLOG: "/blog",
    SERVICES: "/services/",
    PRIVACY_POLICY: "/privacy-policy/",
    TERMS_AND_CONDITIONS: "/terms-and-conditions/",
    SELLER: "/seller/",
    BUYER_PROFILE: "/profile/buyer/",
};